version: '3.9'

networks:
  docker-tarefasfiesc:
    driver: bridge

services:
  BancoTarefasFIESC:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "psql1234"
      POSTGRES_DB: "TarefasFIESC"
    ports:
      - 5432:5432
    command: -p 5432
    networks: 
      - docker-tarefasfiesc
    
  TarefasFIESC:
    depends_on: 
      - BancoTarefasFIESC
    image: tarefasfiesc
    build: .
    environment: 
      DB_CONNECTION_string: "User ID=postgres;Password=psql1234;Host=BancoTarefasFIESC;Port=5432;Database=TarefasFIESC;SslMode=disable;Pooling=true"
    ports:
      - 5000:80
    restart: always
    networks: 
      - docker-tarefasfiesc
